---
- name: Running show commands on Cisco IOS
  hosts: router01
  gather_facts: false
  connection: local # it looks like local is not supported anymore
  # connection: network_cli

  tasks:
    - name: Run multiple commands on Cisco IOS nodes
      ios_command:
        commands:
          - show version
          - show ip int brief

      register: output

    - debug: var=output.stdout_lines



# Description:
# Old method  prior to ansible 2.5 using connection: local instead of connection: network_cli.

# Command to run:
# ansible-playbook -i ./hosts ./ios_command_local.yaml  -u admin -k
# both hosts and yaml files are in the current working directory